# This is a basic workflow to help you get started with Actions

name: Convertigo CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ci ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
    - name: Run Convertigo build
      env:
        C8O_SERVER: ${{ secrets.C8O_SERVER }}
        C8O_USER: ${{ secrets.C8O_USER }}
        C8O_PASSWORD: ${{ secrets.C8O_PASSWORD }}
      run: echo "Build C8oStudio and deploy to $C8O_SERVER" && sh gradlew --no-daemon --stacktrace --info deploy -Pconvertigo.deploy.server=$C8O_SERVER -Pconvertigo.deploy.user=$C8O_USER -Pconvertigo.deploy.password=$C8O_PASSWORD -Pconvertigo.load.mobileApplicationEndpoint=$C8O_SERVER
